import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Player from "@vimeo/player";
import { useEffect, useState } from "react";
import getVideoIdList from "../public/data/getVideoIdList";

const Home: NextPage = () => {
  const videoIdList: string[] = getVideoIdList();
  const [index, setIndex] = useState<number>(0);
  const [videoId, setVideoId] = useState<string>("34818069");

  if (typeof window !== "undefined") {
    const iframe = document.querySelector("iframe");
    if (iframe !== null) {
      const player = new Player(iframe);
      setInterval(() => {
        player
          .getEnded()
          .then(function (ended: boolean) {
            if (ended) {
              // ended = whether or not the video has ended
              console.log(index);
              setIndex(index + 1);
            }
          })
          .catch(function (error: Error) {
            // an error occurred
          });
      }, 1000);
    }
  }

  useEffect(() => {
    setVideoId(videoIdList[index % videoIdList.length]);
  }, [index, videoIdList]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <iframe
          src={`https://player.vimeo.com/video/${videoId}?autoplay=1`}
          width="1200"
          height="640"
          frameBorder="0"
          allowFullScreen={true}
          style={{ background: "black" }}
        ></iframe>
      </main>
    </div>
  );
};

export default Home;
